redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  # volumes:
  #   - ./:/var/www/app
  ports:
    - 3011:3011
  links:
    - redis
  environment:
    - REDIS_URL=redis://cache
    # - NODE_ENV=development
    - PORT=3011
  # command: sh -c 'npm i && node server.js'
